services:
  - type: web
    name: voice-shopping-backend
    env: python
    rootDir: backend
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      gunicorn app:app -b 0.0.0.0:$PORT
