services:
  - type: web
    name: voice-shopping-assistant
    env: python
    rootDir: backend
    buildCommand: |
      # Build React frontend
      cd ../frontend
      npm install
      npm run build
      cd ../backend
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT --workers 2
